version: '2'
services:
  client:
    image: "frondev/client"
    ports:
     - "8080:8080"
    links:
     - auth01
     - auth02
     - auth03
  auth01:
      image: "frondev/authentication"
      ports:
        - "9091:8080"
  auth02:
        image: "frondev/authentication"
        ports:
         - "9092:8080"
  auth03:
        image: "frondev/authentication"
        ports:
         - "9093:8080"