version: '2'
services:
  client:
      image: "frondev/client"
      ports:
          - "8080:8080"
      links:
          - auth01
          - auth02
          - auth03
  auth01:
      image: "frondev/authentication"
  auth02:
        image: "frondev/authentication"
  auth03:
        image: "frondev/authentication"
  #gatling:
  #      image: "denvazh/gatling"
  #      links:
  #        - client
